name: Android CI
on: [push]

jobs:

  test:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'

      - name: config emulator
        run: $HOME/Library/Android/sdk/tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis_playstore;x86" --device "Nexus 4"

      - name: Creat APK
        run: ./gradlew assembleDebug

      - name: Unit Test
        run: ./gradlew jacocoTestProdDebugUnitTestReport

      - name: Linter
        run: ./gradlew lintProdDebug

      - run: ./gradlew copyLintBuildArtifacts
      - run: ./gradlew copyUnitTestBuildArtifacts
      - run: ./gradlew pullProdDebuggableAndroidTestScreenshots -PdisablePreDex

      - run: echo "🍏 This job's status is ${{ job.status }}."


