name: Android CI
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew jacocoTestProdDebugUnitTestReport

      - run: echo "🍏 This job's status is ${{ job.status }}."
