name: Android CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

#      - name: Build Project
#        run: ./gradlew assembleDebug

  Android_CI:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install --user codecov
          pip install --user Pillow==6.2.2

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: gradle/wrapper/

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-28

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          target: google_apis
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          disable-animations: true
          target: google_apis
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            chmod +x gradlew
            ./gradlew jacocoTestProdDebugUnitTestReport

      - name: Run E2E
        if: always()
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          disable-animations: true
          target: google_apis
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            ./gradlew verifyProdDebuggableAndroidTestScreenshotTest -PdisablePreDex

      - name: Run Artifacts
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          disable-animations: true
          target: google_apis
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            ./gradlew copyLintBuildArtifacts
            ./gradlew copyUnitTestBuildArtifacts
            ./gradlew pullProdDebuggableAndroidTestScreenshots -PdisablePreDex

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: SS Reports
          path: OpenEdXMobile/build/screenshotsProdDebuggableAndroidTest

      - name: Generate Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: artifacts

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: OpenEdXMobile/build/reports/coverage/debug

      - name: Upload Test Report
        run: bash <(curl -s https://codecov.io/bash) -f "artifacts/reports/jacoco/jacocoTestProdDebugUnitTestReport/jacocoTestProdDebugUnitTestReport.xml"
