name: Android CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy C! gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

#      - name: Build Project
#        run: ./gradlew assembleDebug

#      - name: Upload build ouputs (APKS)
#        uses: actions/upload-artifact@v2
#        with:
#          name: build-outputs
#          path: OpenEdXMobile/build/outputs/apk/

  test:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [ 30 ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: true
          target: google_apis
          ndk: 21.4.7075529
#          script: ./gradlew jacocoTestProdDebugUnitTestReport
          script: ./gradlew connectedCheck

      - name: Generate Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: OpenEdXMobile/build/reports/coverage/debug

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: OpenEdXMobile/build/reports/coverage/debug

      - name: Upload Test Report
        run: bash <(curl -s https://codecov.io/bash) -f "OpenEdXMobile/build/reports/coverage/debug/report.xml"
